version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: ./rails_mec/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails_mec:/app/
    ports:
      - 3000:3000
      - 587:587
    depends_on:
      - db
  nginx:
    build:
      context: ./
    restart: always
    volumes:
      - ./nginx_logs:/var/log/nginx_logs
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./data:/data
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "5201:5201"
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
      net.ipv4.tcp_tw_reuse: 1
      net.ipv4.tcp_fin_timeout: 20
volumes:
  mysql_data: